# Generated by Django 3.1.2 on 2021-03-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ben', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
