# Generated by Django 3.1.2 on 2021-04-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ben', '0003_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='recommend',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
