# Generated by Django 3.1.2 on 2021-04-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ben', '0004_auto_20210418_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Reviews', 'verbose_name_plural': 'Reviews'},
        ),
    ]
